# Generated by Django 4.1.4 on 2022-12-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "note", "verbose_name_plural": "notes"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="note",
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
