# Generated by Django 4.1.4 on 2022-12-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_menu", "0002_alter_product_options_remove_product_note_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["pk"]},
        ),
    ]
